# Generated by Django 5.2 on 2025-07-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=False, max_length=100, unique=True),
        ),
    ]
