# Generated by Django 5.2 on 2025-07-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='conclusion',
            field=models.TextField(default=False),
        ),
    ]
