# Generated by Django 5.2 on 2025-07-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_blog_conclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='core_concepts',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='main_concept',
            field=models.TextField(default=False),
        ),
    ]
