# Generated by Django 5.2 on 2025-07-08 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_blog_core_concepts_blog_main_concept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='main_concept',
            new_name='partial_applications',
        ),
    ]
